### ISSUE TITLE
Minor refactors of the codebase

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#519]
## 🚀 Refactoring
This is a tracking issue for minor refactors (which makes sure not to change existing APIs):
- pragma (see also: #476)
  - Use `# pragma: no cover` instead of `# pragma: no-cover`.
  - Place `# pragma: no cover` at the beginning of clauses.
- imports
  - Add missing `__all__` to `__init__.py` files.
  - Use if/else instead of `try/except` for optional import statements
  - Raise `ModuleNotFoundError` with helpful messages **when instantiating classes or calling functions** in order not to fail to import classes/functions.

### Progress
- [x] `pl_bolts/callbacks/` #477
- [ ] `pl_bolts/datamodules/` #523
- [ ] `pl_bolts/datasets/` #523
- [ ] `pl_bolts/metrics/` #523
- [ ] `pl_bolts/models/` #524
- [x] `pl_bolts/models/self_supervised/` #479 #482
- [ ] `pl_bolts/optimizers/` #523
- [ ] `pl_bolts/transforms/` #523
- [ ] `pl_bolts/utils/` #523

### Additional context
After addressing this issue, #427 will follow up for major refactoring in models, and I'll add the importing tests in #421.
